// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  customSidebar: [
    // "intro",
    "about",
    {
      type: "category",
      label: "The Very Basics",
      items: [
        "the-very-basics/overview",
        "the-very-basics/understanding-blockchain",
        "the-very-basics/understanding-smart-contracts",
        "the-very-basics/understanding-tokens",
        "the-very-basics/understanding-wallets",
        "the-very-basics/understanding-DAOs",
      ],
    },
    {
      type: "category",
      label: "Get Started with the DAO",
      items: [
        "get-started/overview",
        "get-started/create-an-account",
        "get-started/dao-tokens",
        "get-started/claiming-tasks",
        "get-started/submitting-tasks",
        "get-started/leaderboard",
        "get-started/learn-and-earn",
      ],
    },
    {
      type: "category",
      label: "Contributing Code",
      items: [
        "contribute-code/overview",
        "contribute-code/environment-setup",
        "contribute-code/contribute-to-docs",
        "contribute-code/contribute-to-DAO",
      ],
    },
  ],
};

export default sidebars;
